"""Add tasks table for background job tracking

Revision ID: 4783c098cb54
Revises: 6f878075d78c
Create Date: 2026-02-16 20:07:43.228564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4783c098cb54'
down_revision: Union[str, Sequence[str], None] = '6f878075d78c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=255), nullable=False, comment='Celery task ID (UUID)'),
    sa.Column('task_name', sa.String(length=255), nullable=False, comment='Task function name'),
    sa.Column('task_type', sa.String(length=100), nullable=False, comment="Task category (e.g., 'document_processing')"),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Current task status'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='Task progress percentage (0-100)'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='When task execution started'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When task completed'),
    sa.Column('result', sa.JSON(), nullable=True, comment='Task result data (JSON)'),
    sa.Column('error', sa.Text(), nullable=True, comment='Error message if failed'),
    sa.Column('traceback', sa.Text(), nullable=True, comment='Full error traceback'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of retry attempts'),
    sa.Column('max_retries', sa.Integer(), nullable=False, comment='Maximum retry attempts'),
    sa.Column('resource_type', sa.String(length=100), nullable=True, comment="Type of resource being processed (e.g., 'document')"),
    sa.Column('resource_id', sa.String(length=36), nullable=True, comment='ID of resource being processed'),
    sa.Column('tenant_id', sa.String(length=36), nullable=True, comment='Tenant ID for multi-tenancy'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_resource_id'), 'tasks', ['resource_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=True)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_resource_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
