"""Add documents table

Revision ID: 6f878075d78c
Revises: e864be2f0e52
Create Date: 2026-02-16 17:11:41.569289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f878075d78c'
down_revision: Union[str, Sequence[str], None] = 'e864be2f0e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('title', sa.String(length=500), nullable=False, comment='Document title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Document description'),
    sa.Column('filename', sa.String(length=500), nullable=False, comment='Original filename'),
    sa.Column('file_path', sa.Text(), nullable=False, comment='Storage path (local or S3 key)'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='File size in bytes'),
    sa.Column('mime_type', sa.String(length=255), nullable=False, comment='MIME type (e.g., application/pdf)'),
    sa.Column('file_hash', sa.String(length=64), nullable=True, comment='SHA256 hash for deduplication'),
    sa.Column('document_type', sa.String(length=50), nullable=False, comment='Document type'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Processing status'),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True, comment='When processing started'),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True, comment='When processing completed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if processing failed'),
    sa.Column('text_content', sa.Text(), nullable=True, comment='Extracted text content'),
    sa.Column('page_count', sa.Integer(), nullable=True, comment='Number of pages (for PDFs)'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='Public access flag'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Tenant ID'),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=True, comment='User who uploaded the document'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_tenant_created', 'documents', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_document_tenant_status', 'documents', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_document_tenant_type', 'documents', ['tenant_id', 'document_type'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.create_index(op.f('ix_documents_is_deleted'), 'documents', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_documents_title'), 'documents', ['title'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by_user_id'), 'documents', ['uploaded_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_uploaded_by_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_title'), table_name='documents')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_deleted'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index('idx_document_tenant_type', table_name='documents')
    op.drop_index('idx_document_tenant_status', table_name='documents')
    op.drop_index('idx_document_tenant_created', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
