"""Initial schema: users and tenants

Revision ID: a55ef3edb87e
Revises: 
Create Date: 2026-02-05 17:17:23.155458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a55ef3edb87e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Organization name'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment="URL-friendly identifier (e.g., 'acme-corp')"),
    sa.Column('settings', sa.Text(), nullable=True, comment='JSON settings for tenant-specific config'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Tenant active status'),
    sa.Column('max_users', sa.Integer(), nullable=False, comment='Maximum users allowed'),
    sa.Column('max_documents', sa.Integer(), nullable=False, comment='Maximum documents allowed'),
    sa.Column('max_storage_mb', sa.Integer(), nullable=False, comment='Maximum storage in megabytes'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address (unique)'),
    sa.Column('hashed_password', sa.Text(), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment="User's full name"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Account active status'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Superuser/admin privileges'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Email verification status'),
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Associated tenant ID'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
